//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatModelsDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conversation
    {
        public int Id { get; set; }
        public int AccountID { get; set; }
        public System.DateTime LastOnline { get; set; }
        public string ReceivedMsgs { get; set; }
        public Nullable<System.DateTime> MsgReseivedOn { get; set; }
        public Nullable<bool> IsReplied { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public string SentMsg { get; set; }
        public Nullable<System.DateTime> MsgSentOn { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
